import { CategoryItem } from "~/interfaces/simulation"

export const categoryItems: CategoryItem[] = [
    {
        id: 1,
        category_id: 1,
        name: 'Desing 1',
        value: '/shirts/1.png',
        description: 'design',
    },
    {
        id: 2,
        category_id: 1,
        name: 'Desing 2',
        value: '/shirts/2.png',
        description: 'design',
    },
    {
        id: 3,
        category_id: 1,
        name: 'Desing 3',
        value: '/shirts/3.png',
        description: 'design',
    },
    {
        id: 4,
        category_id: 1,
        name: 'Desing 4',
        value: '/shirts/4.png',
        description: 'design',
    },
    {
        id: 5,
        category_id: 1,
        name: 'Desing 5',
        value: '/shirts/5.png',
        description: 'design',
    },
    {
        id: 6,
        category_id: 2,
        name: 'Light Green Blue',
        value: '#55efc4',
        description: 'colors',
    },
    {
        id: 7,
        category_id: 2,
        name: 'Mint Leaf',
        value: '#00b894',
        description: 'colors',
    },
    {
        id: 8,
        category_id: 2,
        name: 'Faded Poster',
        value: '#81ecec',
        description: 'colors',
    },
    {
        id: 9,
        category_id: 2,
        name: 'Green Darner Tail',
        value: '#74b9ff',
        description: 'colors',
    },
    {
        id: 10,
        category_id: 2,
        name: 'Electron Blue',
        value: '#0984e3',
        description: 'colors',
    },
    {
        id: 11,
        category_id: 2,
        name: 'Shy Moment',
        value: '#a29bfe',
        description: 'colors',
    },
    {
        id: 12,
        category_id: 2,
        name: 'Exodus Fruit',
        value: '#6c5ce7',
        description: 'colors',
    },
    {
        id: 13,
        category_id: 2,
        name: 'City Lights',
        value: '#dfe6e9',
        description: 'colors',
    },
    {
        id: 14,
        category_id: 2,
        name: 'Shooting Breeze',
        value: '#b2bec3',
        description: 'colors',
    },
    {
        id: 15,
        category_id: 2,
        name: 'Sour Lemon',
        value: '#ffeaa7',
        description: 'colors',
    },
    {
        id: 16,
        category_id: 2,
        name: 'Bright Yarrow',
        value: '#fdcb6e',
        description: 'colors',
    },
    {
        id: 17,
        category_id: 2,
        name: 'First Date',
        value: '#fab1a0',
        description: 'colors',
    },
    {
        id: 18,
        category_id: 2,
        name: 'Orangeville',
        value: '#e17055',
        description: 'colors',
    },
    {
        id: 19,
        category_id: 2,
        name: 'Pink Glamour',
        value: '#ff7675',
        description: 'colors',
    },
    {
        id: 20,
        category_id: 2,
        name: 'Chi-gong',
        value: '#d63031',
        description: 'colors',
    },
    {
        id: 21,
        category_id: 2,
        name: 'Pico Pink',
        value: '#fd79a8',
        description: 'colors',
    },
    {
        id: 22,
        category_id: 2,
        name: 'Prunus Avium',
        value: '#e84393',
        description: 'colors',
    },
    {
        id: 23,
        category_id: 2,
        name: 'American River',
        value: '#636e72',
        description: 'colors',
    },
    {
        id: 24,
        category_id: 2,
        name: 'Dracula Orchid',
        value: '#2d3436',
        description: 'colors',
    },
    {
        id: 25,
        category_id: 3,
        name: 'Rhombus',
        value: 'rhombus',
        description: 'patterns',
    },
    {
        id: 26,
        category_id: 3,
        name: 'ZigZag',
        value: 'zig-zag',
        description: 'patterns',
    },
    {
        id: 28,
        category_id: 3,
        name: 'Circles',
        value: 'circles',
        description: 'patterns',
    },
    {
        id: 29,
        category_id: 3,
        name: 'Diagonal Right',
        value: 'diagonal-right',
        description: 'patterns',
    },
    {
        id: 30,
        category_id: 3,
        name: 'Diagonal Left',
        value: 'diagonal-left',
        description: 'patterns',
    },
    //   {
    //       id: 31,
    //       category_id: 3,
    //       name: 'Paper',
    //       value: 'paper',
    //       description: 'patterns',
    //   },
    {
        id: 33,
        category_id: 3,
        name: 'Polka',
        value: 'polka',
        description: 'patterns',
    },
    {
        id: 34,
        category_id: 3,
        name: 'Polka Diamon',
        value: 'polka-diamon',
        description: 'patterns',
    },
    {
        id: 35,
        category_id: 3,
        name: 'Lines',
        value: 'lines',
        description: 'patterns',
    },
    {
        id: 31,
        category_id: 3,
        name: 'Vertical Lines',
        value: 'vertical-lines',
        description: 'patterns',
    },
    {
        id: 27,
        category_id: 4,
        name: '10',
        value: 10,
        description: 'sizes',
    },
    {
        id: 36,
        category_id: 4,
        name: '20',
        value: 20,
        description: 'sizes',
    },
    {
        id: 37,
        category_id: 4,
        name: '40',
        value: 40,
        description: 'sizes',
    },
    {
        id: 38,
        category_id: 4,
        name: '60',
        value: 60,
        description: 'sizes',
    },
    {
        id: 39,
        category_id: 4,
        name: '80',
        value: 80,
        description: 'sizes',
    },
    {
        id: 40,
        category_id: 4,
        name: '100',
        value: 100,
        description: 'sizes',
    },
    {
        id: 41,
        category_id: 5,
        name: 'White',
        value: '#fff',
        description: 'colors',
    },
    {
        id: 42,
        category_id: 5,
        name: 'Gray-50',
        value: '#f5f5f5',
        description: 'colors',
    },
    {
        id: 43,
        category_id: 5,
        name: 'Gray-100',
        value: '#e9e9e9',
        description: 'colors',
    },
    {
        id: 44,
        category_id: 5,
        name: 'Gray-200',
        value: '#d9d9d9',
        description: 'colors',
    },
    {
        id: 45,
        category_id: 5,
        name: 'Gray-300',
        value: '#c4c4c4',
        description: 'colors',
    },
    {
        id: 46,
        category_id: 5,
        name: 'Gray-400',
        value: '#9d9d9d',
        description: 'colors',
    },
    {
        id: 47,
        category_id: 5,
        name: 'Gray-500',
        value: '#7b7b7b',
        description: 'colors',
    },
    {
        id: 48,
        category_id: 5,
        name: 'Gray-600',
        value: '#555555',
        description: 'colors',
    },
    {
        id: 49,
        category_id: 5,
        name: 'Gray-700',
        value: '#434343',
        description: 'colors',
    },
    {
        id: 50,
        category_id: 5,
        name: 'Gray-800',
        value: '#262626',
        description: 'colors',
    },
]

export function simuLoading(time = 1000) {
    return new Promise((resolve) => {
        const tiemout = setTimeout(() => {
            clearTimeout(tiemout)
            resolve('SUCCESS')
        }, time)
    })
}

export default defineEventHandler(async (event) => {
    await simuLoading()
    return categoryItems
})